api/urls.py
from django.conf.urls import url
from .views import *

urlpatterns = [
    url(r'^list/$', PostListAPIView.as_view(), name="list"),
    url(r'^detail/(?P<post_slug>[-\w]+)/$', PostDetailAPIView.as_view(), name="detail"),
    url(r'^delete/(?P<post_slug>[-\w]+)/$', PostDeleteAPIView.as_view(), name="delete"),
    url(r'^create/$', PostCreateAPIView.as_view(), name="create"),
    url(r'^update/(?P<post_slug>[-\w]+)/$', PostUpdateAPIView.as_view(), name="update"),
    url(r'^comment/list/$', CommentListAPIView.as_view(), name="comment_list"),
    url(r'^comment/create/$', CommentCreateAPIView.as_view(), name="comment_create"),
    url(r'^register/$', UserCreateAPIView.as_view(), name="register"),

    ]

blog/urls.py
from django.conf.urls import url , include
from django.contrib import admin
from django.conf import settings 
from django.conf.urls.static import static 


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^posts/', include('post.urls', namespace = "post")),
    url(r'^comments/', include('django_comments.urls')),
    url(r'^api/', include('api.urls', namespace="api")),

    
]
if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
	url(r'^detail/(?P<slug>[-\w]+)$', views.post_detail, name="detail"),
    url(r'^list/$', views.post_list, name="list"),
    url(r'^create/$', views.post_create, name="create"),
    url(r'^update/(?P<slug>[-\w]+)$', views.post_update, name="update"),
    url(r'^delete/(?P<slug>[-\w]+)$', views.post_delete, name="delete"),
    url(r'^home/$', views.post_home, name="home"),
    url(r'^eventcreate/$', views.event_create, name="eventcreate"),
    url(r'^eventlist/$', views.event_list, name="eventlist"),
    url(r'^eventdelete/(?P<event_slug>[-\w]+)$', views.event_delete, name="eventdelete"),
    url(r'^eventeupdate/(?P<event_slug>[-\w]+)$', views.event_update, name="eventupdate"),
    url(r'^signup/$', views.usersignup, name="signup"),
    url(r'^login/$', views.userlogin, name="login"),
    url(r'^logout/$', views.userlogout, name="logout"),
    url(r'^search_bar/$', views.search_bar, name="search_bar"),
   


]

post/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.template.defaultfilters import slugify

# Create your models here.

class Post(models.Model):
	author = models.ForeignKey(User, default=1)
	title = models.CharField(max_length=255)
	content = models.TextField()
	updated = models.DateTimeField(auto_now=True, auto_now_add=False)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add = True)
	image =  models.ImageField(upload_to="blog_images", null=True , blank=True)
	slug = models.SlugField(unique=True, null=True)
	publish = models.DateField()
	draft = models.BooleanField(default=True)

	def __str__(self):
		return self.title

	def get_absoulute_url(self):
		return reverse("post:detail", kwargs={"slug": self.slug})
	def search_id(self, x ):
		s = Post.objects.all().filter(title=x)
		return reverse("post:detail", kwargs={"slug": self.slug})
	def update_url_post(self):
		return reverse("post:update", kwargs={"slug": self.slug})
	def delete_url(self):
		return reverse("post:delete", kwargs={"slug": self.slug})
	def create_url(self):
		return redirect("post:create")
	def croping(self):
		return str(self.content[0:30])
		pass
	def name_val(self):
		return str(self.slug) 
		pass
	class Meta:
		ordering = ['-timestamp','-updated']

class Event(models.Model):
	event_author = models.ForeignKey(User, default=1)
	event_slug = models.SlugField(unique=True, null=True)
	event_name = models.CharField(max_length=160)
	event_detail = models.TextField()
	event_pic = models.ImageField(upload_to="blog_images", null=True , blank=True)
	startdate_event = models.DateField(null=True)
	enddate_event = models.DateField(null=True)
	def __str__(self):
		return self.event_name
	class Meta:
		ordering = ['startdate_event']

def post_reciever(sender, instance, *args, **kwargs):
	if not instance.slug:
		slug=slugify(instance.title)
		qs= Post.objects.filter(slug=slug).order_by("-id")
		if qs.exists():
			slug= "%s-%s"%(slug , instance.id)
		instance.slug = slug 
		instance.save()
def event_reciever(sender, instance , *args, **kwargs):
	if not instance.event_slug:
		slug= slugify(instance.event_name)
		qs= Event.objects.filter(event_slug=slug).order_by("-id")
		if qs.exists():
			slug = "%s-%s"%(slug, instance.id)
		instance.event_slug= slug
		instance.save()
post_save.connect(event_reciever,sender=Event)
post_save.connect(post_reciever,sender=Post)

post/forms.py
from django import forms
from .models import Post ,Event
from django.contrib.auth.models import User 


class PostForm(forms.ModelForm):
	class Meta:
		model = Post
		fields = ['title','content','image','publish','draft']
		widgets={
		        'publish': forms.DateInput(attrs={"type":"date"}),
		        }
class EventForm(forms.ModelForm):
	class Meta:
		model = Event
		fields = ['event_name','event_detail','event_pic','startdate_event','enddate_event']
		widgets={
		        'startdate_event': forms.DateInput(attrs={"type":"date"}),
		        'enddate_event': forms.DateInput(attrs={"type":"date"}),
		        }
class UserSignUp(forms.ModelForm):
	class Meta:
		model = User
		fields = ['username','password']
		widgets= {
			'password': forms.PasswordInput(),
		}
class UserLogin(forms.Form):
	username= forms.CharField(required=True)
	password= forms.CharField(required=True,widget=forms.PasswordInput())

post/views.py
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from .models import Post , Event
from django.shortcuts import get_object_or_404
from .forms import PostForm , UserSignUp ,UserLogin ,EventForm
from django.contrib import messages
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.http import Http404 ,JsonResponse
from django.utils import timezone 
from django.db.models import Q
from django.contrib.auth import authenticate , login ,logout
from datetime import date


def search_bar(request):
    obj = Post.objects.all()
    details = []
    for x in obj:
        details = details + [x.title]
    context = {
    "details": details,
    }
    return JsonResponse(context,safe=False)

def userlogin(request):
    context={}
    form = UserLogin()
    context['form'] = form 
    if request.method == "POST":
        form = UserLogin(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            auth_user= authenticate(username=username,password=password)
            if auth_user is not None:
                login(request,auth_user)
                return redirect("post:home")

            messages.warning(request,"wrong user name or password")
            return redirect("post:login")
        messages.warning(request,form.errors)
        return redirect("post:login")
    return render(request, 'login.html',context)


def usersignup(request):
    context={}
    form = UserSignUp()
    context['form'] = form 
    if request.method == "POST":
        form = UserSignUp(request.POST)
        if form.is_valid():
            user = form.save()
            username = user.username
            password = user.password
            user.set_password(password)
            user.save()
            auth_user= authenticate(username=username,password=password)
            login(request,auth_user)
            return redirect("post:home")
        messages.error(request,form.errors)
        return redirect("post:signup")
    return render(request, 'signup.html',context)

def userlogout(request):
    logout(request)
    return redirect("post:home")


def post_home(request):

    obj = Post.objects.all().first()
    if Event.objects.all().exists():
        today = timezone.now().date()
        event = Event.objects.all()
        x = False
        for y in event:
            if y.startdate_event >= today:
                event = y
                x = True 
                break

        context = {
        "x": x,
        "today": today,
        "user": request.user,
        "last_event": event,
        "post_last": obj,
        }
    else:
        context = {
        "user": request.user,
        "post_last": obj,
        }
    return render(request, 'post_home.html', context)
def post_detail(request, slug):
    obj = get_object_or_404(Post , slug=slug)
    today = timezone.now().date()
    if obj.publish > today or obj.draft:
        if not(request.user.is_superuser or request.user.is_staff):
            raise Http404
    context = {
        "instance": obj,
        "user": request.user,
    }
    return render(request, 'post_detail.html',context)

def post_list(request):
    today = timezone.now().date()
    if request.user.is_superuser or request.user.is_staff :
        details = Post.objects.all()
    else:
        details = Post.objects.filter(draft=False).filter(publish__lte=today)
    
    query = request.GET.get("q")
    if query:
        details= details.filter(
            Q(title__icontains=query) | 
            Q(content__icontains=query) |
            Q(author__first_name__icontains=query) | 
            Q(author__last_name__icontains=query)
            ).distinct()
    paginator = Paginator(details, 4) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)

    context3 = {
        
        "user": request.user,
        "list": contacts,
        "today": today,
    }
    return render(request, 'post_list.html',context3)

def post_create(request):
    if not (request.user.is_staff or request.user.is_superuser):
        raise Http404
    form = PostForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        obj = form.save(commit= False)
        obj.author = request.user 
        obj.save()
        messages.success(request,"your post has been created")
        return redirect ("post:list")
    context = {
    "form": form,
    "user": request.user
    }
    return render(request, 'post_create.html',context)
    return render(request, 'post_create.html',context)
def post_update(request, slug):
    obj = get_object_or_404(Post, slug=slug)
    form = PostForm(request.POST or None ,request.FILES or None , instance=obj)
    if form.is_valid():
        form.save()
        messages.success(request,"the post has been updated")
        return redirect("post:list")
    context = {
        "form": form,
        "obj": obj,
        "user": request.user,
    }
    return render(request, 'post_update.html', context)

def post_delete(request, slug):
    post_obj = Post.objects.get(slug=slug)
    post_obj.delete()
    messages.warning(request, "the post has been deleted")
    return redirect("post:list")

def event_create(request):
    if not (request.user.is_staff or request.user.is_superuser):
        raise Http404
    form = EventForm(request.POST or None, request.FILES or None)
    if form.is_valid():
        form.save()
        return redirect("post:eventlist")
    context = {
    "form": form,
    "user": request.user,
    }
    return render(request,'event_create.html',context)
def event_list(request):
    details = Event.objects.all()
    paginator = Paginator(details, 4) # Show 25 contacts per page

    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        contacts = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        contacts = paginator.page(paginator.num_pages)

    context3 = {
        "list": contacts,
        "user": request.user,
    }
    return render(request, 'event_list.html',context3)

def event_delete(request, event_slug):
    post_obj = Event.objects.get(event_slug=event_slug)
    post_obj.delete()
    messages.warning(request, "the post has been deleted")
    return redirect("post:eventlist")
def event_update(request, event_slug):
    obj = get_object_or_404(Event, event_slug=event_slug)
    form = EventForm(request.POST or None ,request.FILES or None , instance=obj)
    if form.is_valid():
        form.save()
        messages.success(request,"the post has been updated")
        return redirect("post:eventlist")
    context = {
    "user": request.user,
    "form": form,
    "obj": obj,
    }
    return render(request, 'event_update.html', context)

post/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>
		{% block head_title %}
		{% endblock head_title %}
	</title>
	{% block head_link %}
		{% endblock head_link %}
	
	<link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static 'css/234.css' %}">
	<link rel="stylesheet" type="text/css" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/smoothness/jquery-ui.css">
</head>
<body>
		<ul class="nav nav-tabs">
            <li role="presentation" class="active"><a href="{%url 'post:home'%}">Home</a></li>
            <li role="presentation"><a href="{%url 'post:list'%}">list</a></li>
            
            <li role="presentation"><a href="{%url 'post:eventlist'%}">events</a></li>
            <li role="presentation"><a href="{%url 'post:login'%}">login</a></li>
            <li role="presentation"><a href="{%url 'post:signup'%}">signup</a></li>
            <li role="presentation"><a href="{%url 'post:logout'%}">logout</a></li>
            {% if user.is_superuser or user.is_staff %}
            	<li role="presentation"><a href="{%url 'post:create'%}">create post</a></li>
            {% endif %}
            

        </ul>
	
	{% include 'facebook.html' %}
	{% include 'messgese.html' %}
	{%if user.is_superuser or user.is_staff%}
		 {% include 'navbar.html' %}
	{% endif%}
	 <div class="container content">
		{% block content %}



		{% endblock content%}
	</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jqueryui/1/jquery-ui.min.js"></script>
<script type="text/javascript">


    jQuery(function($)
     {
     	var data = [];
     	$.ajax(
            {
                type:'GET',
                url: '{% url "post:search_bar"  %}',
                error: function(){
                    console.log('error');
                },
                success: function(x){
                    console.log('success');
                    for (i=0 ; i < x.details.length ; i++ ){
                    	data.push(x.details[i])
                    }
                    console.log(data)

                },
            }
        );
        
        $("#search_bar").autocomplete({
            source: data
        });
    });
</script>
	<script src="{% static 'js/jquery-3.2.1.min.js'%}"></script>
	<script src="{% static 'js/bootstrap.min.js'%}"></script>
</body>
</html>

post/templates/django_comments.html
{% load comments %}
{% get_comment_list for instance as x %}

            {% for comment in x %}
                <div class="alert alert-info">{{comment.user_name}} said:{{comment.comment}}</div>
                
            {% endfor %}
            {% get_comment_form for instance as form %}
            <form action="{% comment_form_target %}" method="POST">
            
            	
            
            {% csrf_token %}
                <input type="hidden" name="name" value="{{request.user.username}}">
                <input type="hidden" name="email" value="{{request.user.email}}">
               <!-- {# <input type="text" class="form-control input-lg" name="comment"> #}-->
                <textarea type="text" class="form-control input-lg" name="comment"> </textarea>
                {{form.content_type}}
                {{form.object_pk}}
                {{form.timestamp}}
                {{form.security_hash}}
                <input type="hidden" name="next" value="{{instance.get_absoulute_url}}">
                <input type="submit" name="submit" class="btn btn-primary">
            </form>
            

post/templates/event_create.html
{% extends "base.html" %}
{% block content %}
{% load crispy_forms_tags %}
	{% block head_title %}create{% endblock head_title %}
	

<div class="row">
	<form method="POST" action="{% url 'post:eventcreate' %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="create post">
	</form>
</div>
{% endblock content%}

post/templates/event_update.html
{% extends "base.html" %}
{% block content %}
	{% block head_title %}update
	{% endblock head_title %}

	<form method="POST" action="{% url 'post:eventupdate' event_slug=obj.event_slug %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Update post">
	</form>
{% endblock content%}

post/templates/facebook.html
<div id="fb-root"></div>
<script>(function(d, s, id) {
  var js, fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) return;
  js = d.createElement(s); js.id = id;
  js.src = "//connect.facebook.net/en_US/sdk.js#xfbml=1&version=v2.10";
  fjs.parentNode.insertBefore(js, fjs);
}(document, 'script', 'facebook-jssdk'));</script>

post/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	{% block head_title %}login
	{% endblock head_title %}

	<form method="POST" action="{% url 'post:login'  %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form}}
		<input type="submit" value="login">
	</form>
{% endblock content%}

post/templates/messgese.html
{% if messages %}
        <div class="messages">
            {% for message in messages %}
            <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %}>{{ message }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            </div>
            {% endfor %}
        </div>
        {% endif %}
        

post/templates/navbar.html
<nav class="navbar navbar-default">
<form class="navbar-form navbar-left" action="{% url 'post:list'  %}" method="GET">
        <div class="form-group">
          <input type="text" name="q" id="search_bar" placeholder="Search posts here" value="{{request.GET.q}}">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
</nav>

post/templates/post_create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	
	{% block head_title %}create{% endblock head_title %}
	

<div class="row">
	<form method="POST" action="{% url 'post:create' %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="create post">
	</form>
</div>
{% endblock content%}

post/templates/post_detail.html
{% extends "base.html" %}
{% block head_title %}detail{% endblock head_title %}   
{% block head_link %}
   {% endblock head_link %}   
{% block content %}
{% load urlfy %}


    	
        <div class="jumbotron">
    		<div class ="#f48fb1 pink lighten-3">
        		<h2>{{instance.title}}</h2>
        		<p>{{instance.content|linebreaks}}</p>
        		<p>{{instance.timestamp}}</p>
        		<a href={{instance.update_url_post}} class="btn btn-primary">Updating the post </a>
                {% if instance.image %}
                    <a href="#" class="thumbnail">
                        <img src="{{instance.image.url}}" alt="...">
                    </a>
                {% endif %}
                <a href="https://www.facebook.com/sharer/sharer.php?u={{request.build_absolute_uri}}" class="btn btn-info">
                    Share on Facebook
                </a>
                {{share_string}}
                <a href="https://twitter.com/home?status={{instance.content|urlfy}}%20{{request.build_absolute_uri}}" class="btn btn-info">
                     Share on Twitter
                </a>
                <a href="https://www.linkedin.com/shareArticle?mini=true&url={{request.build_absolute_uri}}&title={{instance.title|urlfy}}&summary={{instance.content|urlfy}}&source={{request.build_absolute_uri}}" class="btn btn-info">
                    Share on Linkedin
                </a>

    		</div>
        </div>  
    }
<!-- facebook likes and comments-->
<div class="fb-like" data-href="{{request.build_absolute_uri}}" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>
<div class="fb-comments" data-href="{{request.build_absolute_uri}}" data-numposts="5"></div>
    	<a href="{% url 'post:list' %} " class="btn btn-primary">Go back to the list</a>

{% if request.user.is_authenticated %}       
{% include 'django_comments.html' %}
{% else %}
    <h3>login to post</h3>
{% endif %}    
{% endblock content%}

post/templates/post_home.html
{% extends "base.html" %}
{% block head_title %}Home{% endblock head_title %}
{% block head_link %}
   {% endblock head_link %}   
{% block content %}

<div class="page-header">
<h1>WELCOME TO AHMAD ALI POST<small>....dont judge me</h1>
   </div> 	
<div class="jumbotron">
  
  <div class ="card-panel teal lighten-2">
            
                <a href={{post_last.get_absoulute_url}}><h2>{{post_last.title}}</h2></a>
                <p>{{post_last.content|linebreaks}}</p>
                <p>{{post_last.timestamp}}</p>
                <a href={{post_last.update_url_post}} class="btn btn-info">Updating the post </a>
                {% if post_last.image %}
                    <a href="#" class="thumbnail">
                        <img src="{{post_last.image.url}}" alt="...">
                    </a>
                {% endif %}

            </div>
{% if x %}
    

    <div class="jumbotron">
        <h1>Upcoming Event</h1>
        <div class ="#7986cb indigo lighten-2">
            <h3>{{last_event.event_name}}</h3>
            <h2>{{last_event.event_detail}}</h2>
            {% if last_event.event_pic %}
                <img class="responsive-img" src="{{last_event.evenet_pic.url}}">
            {% endif %}
            <cite>time the event start</cite><p>{{last_event.startdate_event}}</p>
            <cite>time event ends</cite><p>{{last_event.enddate_event}}</p>

        </div>
    </div>
    {% endif %}
{% endblock content%}

post/templates/post_list.html
{% extends "base.html" %}
{% block head_title %}My lists{% endblock head_title %}
{% block head_link %}
   {% endblock head_link %}   
{% block content %}

    
        <div class="row"> 
           {% for x in list%}
                
                <div class="col s6" >
                    <div class="jumbotron">
                        <div class="thumbnail">
                            <div class="caption">
                                    <a href={{x.get_absoulute_url}}><h3>{{x.title}}</h3></a>
                                    <h4>{{x.publish|timesince}}</h4>

                                    <div class="well"><cite>the id of the post:</cite><p>{{x.name_val}}</p>
                                    <p>{{x.content|truncatechars:10}}</p>
                                    <p>{{x.updated}}</p>
                                    <p>{{x.timestamp}}</p>
                                    </div>
                                    {% if x.image %}
                                        <a href="#" class="thumbnail">
                                            <img src="{{x.image.url}}" alt="...">
                                         </a>
                                    {% endif %}
                                    {% if user.is_superuser or user.is_staff %}
                                        <div class="dropdown">
                                        <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                                                                                                    Actions
                                        <span class="caret"></span>
                                        </button>
                                        <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                                            <li><a href={{x.update_url_post}}>Update your post</a></li>
                                            <li><a href="{% url 'post:delete' slug=x.slug %}">DELETE</a></li>
                                        </ul>

                                    </div>
                                        
                                    {% endif %}
                                    
                            </div>
                        </div>
                    </div>
                </div>

           {% endfor %}
        </div> 
    {% if user.is_superuser or user.is_staff %}
        <a href="{% url 'post:create' %}" class= "btn btn-floating pulse"><i class="glyphicon glyphicon-plus" ></i>Create a new Page</a>
    {% endif %}
{#this is where i place my pagintatio which make the pages show less posts #}
<div class="homepage">
    <a href="{%url 'post:home'%}">HOME PAGE</a>
</div>
<div class="pagination">
    <span class="step-links">
        {% if list.has_previous %}
            <a href="?page={{ list.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ list.number }} of {{ list.paginator.num_pages }}.
        </span>

        {% if list.has_next %}
            <a href="?page={{ list.next_page_number }}">next</a>
        {% endif %}
    </span>
</div>

{% endblock content%}

post/templates/post_update.html
{% extends "base.html" %}
{% block content %}
	{% block head_title %}update
	{% endblock head_title %}

	<form method="POST" action="{% url 'post:update' slug=obj.slug %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form.as_p}}
		<input type="submit" value="Update post">
	</form>
{% endblock content%}

post/templates/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
	{% block head_title %}update
	{% endblock head_title %}

	<form method="POST" action="{% url 'post:signup'  %}" enctype="multipart/form-data">
		{% csrf_token %}
		{{form|crispy}}
		<input type="submit" value="signup">
	</form>
{% endblock content%}